# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sigsh\Documents\testPyQt5\ToggleMenu\ToggleMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToggleMenu(object):
    def setupUi(self, ToggleMenu):
        ToggleMenu.setObjectName("ToggleMenu")
        ToggleMenu.resize(1021, 567)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/airplay.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ToggleMenu.setWindowIcon(icon)
        # ToggleMenu.setStyleSheet("background-color: rgb(45, 45, 45);")
        ToggleMenu.setStyleSheet("background-color: white;")

        self.main_layout = QtWidgets.QVBoxLayout(ToggleMenu)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")

        self.top_frame = QtWidgets.QFrame(ToggleMenu)
        self.top_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        # self.top_frame.setStyleSheet("background-color: rgb(35,35,35);")
        self.top_frame.setStyleSheet("background-color: yellow;")
        self.top_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")

        self.layout_top_frame = QtWidgets.QHBoxLayout(self.top_frame)
        self.layout_top_frame.setContentsMargins(0, 0, 0, 0)
        self.layout_top_frame.setSpacing(0)
        self.layout_top_frame.setObjectName("layout_top_frame")

        self.top_frame_anak = QtWidgets.QFrame(self.top_frame)
        self.top_frame_anak.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_frame_anak.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_anak.setObjectName("frame")

        self.layout_top_frame_anak = QtWidgets.QHBoxLayout(self.top_frame_anak)
        self.layout_top_frame_anak.setContentsMargins(0, 0, 0, 0)
        self.layout_top_frame_anak.setSpacing(0)
        self.layout_top_frame_anak.setObjectName("layout_top_frame_anak")
        self.pushButton_toggle_menu = QtWidgets.QPushButton(self.top_frame_anak)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_toggle_menu.sizePolicy().hasHeightForWidth())

        self.pushButton_toggle_menu.setSizePolicy(sizePolicy)
        self.pushButton_toggle_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_toggle_menu.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_toggle_menu.setStyleSheet("""
QPushButton{
    border: 0px solid
}
QPushButton:hover{
    background-color: rgb(45, 45, 45);
}
QPushButton:pressed{
    /*background-color: rgb(85,170, 255);*/
    background: rgb(85, 170, 255);
}
""")
        self.pushButton_toggle_menu.setText("")

        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_toggle_menu.setIcon(icon1)
        self.pushButton_toggle_menu.setObjectName("pushButton_toggle_menu")
        self.layout_top_frame_anak.addWidget(self.pushButton_toggle_menu)

        self.layout_top_frame.addWidget(self.top_frame_anak, 0, QtCore.Qt.AlignLeft)
        self.main_layout.addWidget(self.top_frame)

        # ToggleMenu => button_frame => frame_pages
        # frame utama
        self.frame_content_at_bottom = QtWidgets.QFrame(ToggleMenu)
        self.frame_content_at_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_at_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_at_bottom.setObjectName("frame_content_at_bottom")

        # layout utk frame utama
        self.layout_frame_content_at_bottom = QtWidgets.QHBoxLayout(self.frame_content_at_bottom)
        self.layout_frame_content_at_bottom.setContentsMargins(0, 0, 0, 0)
        self.layout_frame_content_at_bottom.setSpacing(0)
        self.layout_frame_content_at_bottom.setObjectName("layout_frame_content_at_bottom")

        # pada frame utama
        # ada frame left, di atasnya (child) bikin frame TOP left utk hold menu
        self.frame_content_kiri = QtWidgets.QFrame(self.frame_content_at_bottom)
        self.frame_content_kiri.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_content_kiri.setMaximumSize(QtCore.QSize(155, 16777215))
        # self.frame_content_kiri.setStyleSheet("background-color: rgb(35,35,35);")
        self.frame_content_kiri.setStyleSheet("background-color: red;")
        self.frame_content_kiri.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_kiri.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_kiri.setObjectName("frame_content_kiri")

        self.frame_menu_content_kiri = QtWidgets.QFrame(self.frame_content_kiri)
        self.frame_menu_content_kiri.setGeometry(QtCore.QRect(0, 0, 155, 120))
        self.frame_menu_content_kiri.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_menu_content_kiri.setMaximumSize(QtCore.QSize(155, 16777215))
        self.frame_menu_content_kiri.setStyleSheet("""
QPushButton{
    background-repeat: no-repeat;
    background-position: left;
    background-origin: content;
    padding-left: 25px;
    border:none;
    color: rgb(255,255,255);
    background-color: rgb(35,35,35);
    font-size: 12px;
    padding-right: -40px;
}
QPushButton:hover{
    background-color: rgb(45, 45, 45);
}
QPushButton:checked{
    padding-left: 21px;
    border-left: 4px solid rgb(85, 170, 255);
}
""")
        self.frame_menu_content_kiri.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menu_content_kiri.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_content_kiri.setObjectName("frame_menu_content_kiri")

        self.layout_menu_content_kiri = QtWidgets.QVBoxLayout(self.frame_menu_content_kiri)
        self.layout_menu_content_kiri.setContentsMargins(0, 0, 0, 0)
        self.layout_menu_content_kiri.setSpacing(0)
        self.layout_menu_content_kiri.setObjectName("layout_menu_content_kiri")

        # HOME MENU
        self.pushButton_home = QtWidgets.QPushButton(self.frame_menu_content_kiri)
        self.pushButton_home.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_home.setFont(font)
        self.pushButton_home.setStyleSheet("QPushButton{ background-image: url(:/icons/home.svg); }")
        self.pushButton_home.setCheckable(True)
        self.pushButton_home.setChecked(True)
        self.pushButton_home.setObjectName("pushButton_home")
        self.layout_menu_content_kiri.addWidget(self.pushButton_home)

        # USER MENU
        self.pushButton_user = QtWidgets.QPushButton(self.frame_menu_content_kiri)
        self.pushButton_user.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_user.setStyleSheet("QPushButton{ background-image: url(:/icons/user.svg); }")
        self.pushButton_user.setCheckable(True)
        self.pushButton_user.setChecked(False)
        self.pushButton_user.setObjectName("pushButton_user")
        self.layout_menu_content_kiri.addWidget(self.pushButton_user)

        # SETTING MENU
        self.pushButton_setting = QtWidgets.QPushButton(self.frame_menu_content_kiri)
        self.pushButton_setting.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_setting.setStyleSheet("QPushButton{ background-image: url(:/icons/settings.svg); }")
        self.pushButton_setting.setCheckable(True)
        self.pushButton_setting.setChecked(False)
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.layout_menu_content_kiri.addWidget(self.pushButton_setting)

        self.layout_frame_content_at_bottom.addWidget(self.frame_content_kiri)

        # frame kanan = content (alih2 sidebar/menu)
        self.frame_content_kanan = QtWidgets.QFrame(self.frame_content_at_bottom)
        self.frame_content_kanan.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_kanan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_kanan.setObjectName("frame_content_kanan")

        self.layout_content_kanan_stackedwidget = QtWidgets.QHBoxLayout(self.frame_content_kanan)
        self.layout_content_kanan_stackedwidget.setContentsMargins(0, 0, 0, 0)
        self.layout_content_kanan_stackedwidget.setSpacing(0)
        self.layout_content_kanan_stackedwidget.setObjectName("layout_content_kanan_stackedwidget")

        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_content_kanan)
        self.stackedWidget.setObjectName("stackedWidget")

        # PAGE 1 (HOME)
        self.widget_home = QtWidgets.QWidget()
        self.widget_home.setObjectName("widget_home")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_home)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.widget_home)
        self.label.setStyleSheet("font: 28pt \"Cascadia Mono\"; qproperty-alignment: AlignCenter; color: white;")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.stackedWidget.addWidget(self.widget_home)

        # PAGE 2 (USER)
        self.widget_user = QtWidgets.QWidget()
        self.widget_user.setObjectName("widget_user")
        self.textEdit = QtWidgets.QTextEdit(self.widget_user)
        self.textEdit.setGeometry(QtCore.QRect(230, 180, 271, 51))
        self.textEdit.setObjectName("textEdit")
        self.radioButton = QtWidgets.QRadioButton(self.widget_user)
        self.radioButton.setGeometry(QtCore.QRect(540, 210, 93, 16))
        self.radioButton.setObjectName("radioButton")
        self.checkBox = QtWidgets.QCheckBox(self.widget_user)
        self.checkBox.setGeometry(QtCore.QRect(680, 210, 75, 16))
        self.checkBox.setObjectName("checkBox")
        self.stackedWidget.addWidget(self.widget_user)

        # PAGE 3 (SETTING)
        self.widget_setting = QtWidgets.QWidget()
        self.widget_setting.setObjectName("widget_setting")
        self.layout_widget_setting = QtWidgets.QHBoxLayout(self.widget_setting)
        self.layout_widget_setting.setContentsMargins(0, 0, 0, 0)
        self.layout_widget_setting.setSpacing(0)
        self.layout_widget_setting.setObjectName("layout_widget_setting")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.widget_setting)
        self.calendarWidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.layout_widget_setting.addWidget(self.calendarWidget)
        self.stackedWidget.addWidget(self.widget_setting)

        self.layout_content_kanan_stackedwidget.addWidget(self.stackedWidget)
        self.layout_frame_content_at_bottom.addWidget(self.frame_content_kanan)
        self.main_layout.addWidget(self.frame_content_at_bottom)

        # ACTIVATE PAGE 1
        self.retranslateUi(ToggleMenu)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ToggleMenu)

    def retranslateUi(self, ToggleMenu):
        _translate = QtCore.QCoreApplication.translate
        ToggleMenu.setWindowTitle(_translate("ToggleMenu", "Form"))
        self.pushButton_home.setText(_translate("ToggleMenu", "HOME"))
        self.pushButton_user.setText(_translate("ToggleMenu", "USER"))
        self.pushButton_setting.setText(_translate("ToggleMenu", "SETTING"))
        self.label.setText(_translate("ToggleMenu", "Hello PyQt"))
        self.radioButton.setText(_translate("ToggleMenu", "RadioButton"))
        self.checkBox.setText(_translate("ToggleMenu", "CheckBox"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ToggleMenu = QtWidgets.QWidget()
    ui = Ui_ToggleMenu()
    ui.setupUi(ToggleMenu)
    ToggleMenu.show()
    sys.exit(app.exec_())
