kz: C:\work\kenza\nC:\Users\usef\work\sidoarjo\data\kenza
kz1: C:\work\kenza
kz2: C:\Users\usef\work\sidoarjo\data\kenza
a: first
b:
  - second
  - third
c: c:\work\ciledug\ciledug
f: C:\work\fmusmania
g: c:\github
h: c:\hapus
h1: C:\work\kenza\fmus\helpers\python
h2: C:\work\kenza\capcay